language: rust
sudo: true

cache:
  cargo: true
  apt: true

rust:
  - stable

env:
  global:
    # - RUSTFLAGS="-C link-dead-code"
    - OPENSSL_VERSION=openssl-1.0.2

before_install:
  - sudo add-apt-repository -y ppa:0k53d-karl-f830m/openssl
  - sudo apt-get update -qq
  - sudo apt-get install -y openssl libssl-dev libelf-dev libdw-dev cmake gcc binutils-dev libiberty-dev

# Add clippy
before_script:
  - export PATH=$PATH:~/.cargo/bin

script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" != "stable" ]]; then
    cargo clean
    cargo test --features="alpn,tls" -- --nocapture
    fi
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    USE_SKEPTIC=1 cargo tarpaulin --features="alpn,tls" --out Xml --no-count
    bash <(curl -s https://codecov.io/bash)
    echo "Uploaded code coverage"
    fi